site_name: "phenopackets in linkml EXPERIMENTAL DEMO"
theme:
  name: material
  analytics:
    gtag: G-2SYBSJVZ23
  palette:
    scheme: slate
    primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home: home.md
  - Index: index.md
  - Credits: credits.md
site_url: https://cmungall.github.io/linkml-phenopackets/
repo_url: https://github.com/cmungall/linkml-phenopackets/
